package utils;

import clases.comidas.Ingrediente;

public class Variables{

	public static final Ingrediente[] ingredientes = {
		new Ingrediente("Aceitunas negras","0", "349"),
		new Ingrediente("Aceitunas verdes","0", "132"),
		new Ingrediente("Acelgas","0", "33"),
		new Ingrediente("Ajos","0", "169"),
		new Ingrediente("Alcachofas","0", "64"),
		new Ingrediente("Apio","0", "20"),
		new Ingrediente("Berenjena","0", "29"),
		new Ingrediente("Berros","0", "21"),
		new Ingrediente("Brócoli","0", "31"),
		new Ingrediente("Calabacín","0", "31"),
		new Ingrediente("Calabaza","0", "24"),
		new Ingrediente("Cebolla","0", "47"),
		new Ingrediente("Cebolla tierna","0", "39"),
		new Ingrediente("Champiñón y otras setas","0", "28"),
		new Ingrediente("Col","0", "28"),
		new Ingrediente("Col de Bruselas","0", "54"),
		new Ingrediente("Coliflor","0", "30"),
		new Ingrediente("Endibia","0", "22"),
		new Ingrediente("Escarola","0", "37"),
		new Ingrediente("Espárragos","0", "26"),
		new Ingrediente("Espárragos en lata","0", "24"),
		new Ingrediente("Espinaca","0", "32"),
		new Ingrediente("Espinacas congeladas","0", "25"),
		new Ingrediente("Habas tiernas","0", "64"),
		new Ingrediente("Hinojo","0", "16"),
		new Ingrediente("Lechuga","0", "18"),
		new Ingrediente("Nabos","0", "29"),
		new Ingrediente("Papas cocidas","0", "86"),
		new Ingrediente("Pepino","0", "12"),
		new Ingrediente("Perejil","0", "55"),
		new Ingrediente("Pimiento","0", "22"),
		new Ingrediente("Porotos verdes","0", "21"),
		new Ingrediente("Puerros","0", "42"),
		new Ingrediente("Rábanos","0", "20"),
		new Ingrediente("Remolacha","0", "40"),
		new Ingrediente("Repollo","0", "19"),
		new Ingrediente("Rúcula","0", "37"),
		new Ingrediente("Soja, Brotes de","0", "50"),
		new Ingrediente("Tomate triturado en conserva","0", "39"),
		new Ingrediente("Tomates","0", "22"),
		new Ingrediente("Trufa","0", "92"),
		new Ingrediente("Zanahoria","0", "42"),
		new Ingrediente("Zumo de tomate","0", "21"),
		new Ingrediente("Arándanos","0", "41"),
		new Ingrediente("Caqui","0", "64"),
		new Ingrediente("Cereza","0", "47"),
		new Ingrediente("Chirimoya","0", "78"),
		new Ingrediente("Ciruela","0", "44"),
		new Ingrediente("Ciruela seca","0", "290"),
		new Ingrediente("Coco","0", "646"),
		new Ingrediente("Dátil","0", "279"),
		new Ingrediente("Dátil seco","0", "306"),
		new Ingrediente("Frambuesa","0", "40"),
		new Ingrediente("Fresas","0", "36"),
		new Ingrediente("Granada","0", "65"),
		new Ingrediente("Grosella","0", "37"),
		new Ingrediente("Higos","0", "80"),
		new Ingrediente("Higos secos","0", "275"),
		new Ingrediente("Kiwi","0", "51"),
		new Ingrediente("Limón","0", "39"),
		new Ingrediente("Mandarina","0", "40"),
		new Ingrediente("Mango","0", "57"),
		new Ingrediente("Manzana","0", "52"),
		new Ingrediente("Melón","0", "31"),
		new Ingrediente("Mora","0", "37"),
		new Ingrediente("Naranja","0", "44"),
		new Ingrediente("Nectarina","0", "64"),
		new Ingrediente("Nísperos","0", "97"),
		new Ingrediente("Papaya","0", "45"),
		new Ingrediente("Pera","0", "61"),
		new Ingrediente("Piña","0", "51"),
		new Ingrediente("Piña en almíbar","0", "84"),
		new Ingrediente("Plátano","0", "90"),
		new Ingrediente("Pomelo","0", "30"),
		new Ingrediente("Sandía","0", "30"),
		new Ingrediente("Uva","0", "81"),
		new Ingrediente("Uva pasa","0", "324"),
		new Ingrediente("Zumo de fruta","0", "45"),
		new Ingrediente("Zumo de Naranja","0", "42"),
		new Ingrediente("Almendras","0", "620"),
		new Ingrediente("Avellanas","0", "675"),
		new Ingrediente("Castañas","0", "199"),
		new Ingrediente("Maní","0", "560"),
		new Ingrediente("Nueces","0", "660"),
		new Ingrediente("Piñones","0", "660"),
		new Ingrediente("Pistacho","0", "581"),
		new Ingrediente("Cuajada","0", "92"),
		new Ingrediente("Flan de huevo","0", "126"),
		new Ingrediente("Flan de vainilla","0", "102"),
		new Ingrediente("Helados lácteos","0", "167"),
		new Ingrediente("Leche condensada c/azúcar","0", "350"),
		new Ingrediente("Leche condensada s/azúcar","0", "160"),
		new Ingrediente("Leche de cabra","0", "72"),
		new Ingrediente("Leche de oveja","0", "96"),
		new Ingrediente("Leche descremada","0", "36"),
		new Ingrediente("Leche en polvo descremada","0", "373"),
		new Ingrediente("Leche en polvo entera","0", "500"),
		new Ingrediente("Leche entera","0", "68"),
		new Ingrediente("Leche semi descremada","0", "49"),
		new Ingrediente("Mousse","0", "177"),
		new Ingrediente("Nata o crema de leche","0", "298"),
		new Ingrediente("Queso blanco desnatado","0", "70"),
		new Ingrediente("Queso Brie","0", "263"),
		new Ingrediente("Queso cammembert","0", "312"),
		new Ingrediente("Queso cheddar","0", "381"),
		new Ingrediente("Queso crema","0", "245"),
		new Ingrediente("Queso de bola","0", "349"),
		new Ingrediente("Queso de Burgos","0", "174"),
		new Ingrediente("Queso de oveja","0", "245"),
		new Ingrediente("Queso edam","0", "306"),
		new Ingrediente("Queso emmental","0", "415"),
		new Ingrediente("Queso fundido untable","0", "285"),
		new Ingrediente("Queso gruyere","0", "391"),
		new Ingrediente("Queso manchego","0", "376"),
		new Ingrediente("Queso mozzarella","0", "245"),
		new Ingrediente("Queso parmesano","0", "393"),
		new Ingrediente("Queso ricota","0", "400"),
		new Ingrediente("Queso roquefort","0", "405"),
		new Ingrediente("Requesón","0", "96"),
		new Ingrediente("Yogur desnatado","0", "45"),
		new Ingrediente("Yogur desnatado con frutas","0", "82"),
		new Ingrediente("Yogur enriquecido con nata","0", "65"),
		new Ingrediente("Yogur natural","0", "62"),
		new Ingrediente("Yogur natural con fruta","0", "100"),
		new Ingrediente("Bacon (Panceta ahumada)","0", "665"),
		new Ingrediente("Butifarra cocida","0", "390"),
		new Ingrediente("Butifarra, salchicha fresca","0", "326"),
		new Ingrediente("Cabrito","0", "127"),
		new Ingrediente("Cerdo, chuleta","0", "330"),
		new Ingrediente("Cerdo, hígado","0", "153"),
		new Ingrediente("Cerdo, lomo","0", "208"),
		new Ingrediente("Chicharrón","0", "601"),
		new Ingrediente("Chorizo","0", "468"),
		new Ingrediente("Ciervo","0", "120"),
		new Ingrediente("Codorniz y perdiz","0", "114"),
		new Ingrediente("Conejo, liebre","0", "162"),
		new Ingrediente("Cordero lechón","0", "105"),
		new Ingrediente("Cordero pierna","0", "98"),
		new Ingrediente("Cordero, costillas","0", "215"),
		new Ingrediente("Cordero, hígado","0", "132"),
		new Ingrediente("Faisán","0", "144"),
		new Ingrediente("Foie-Gras","0", "518"),
		new Ingrediente("Gallina","0", "369"),
		new Ingrediente("Hamburguesa","0", "230"),
		new Ingrediente("Jabalí","0", "107"),
		new Ingrediente("Jamón","0", "380"),
		new Ingrediente("Jamón cocido","0", "126"),
		new Ingrediente("Jamón crudo","0", "296"),
		new Ingrediente("Jamón York","0", "289"),
		new Ingrediente("Lengua de vaca","0", "191"),
		new Ingrediente("Lomo embuchado","0", "380"),
		new Ingrediente("Mortadela","0", "265"),
		new Ingrediente("Pato","0", "200"),
		new Ingrediente("Pavo, Muslo","0", "186"),
		new Ingrediente("Pavo, Pechuga","0", "134"),
		new Ingrediente("Perdiz","0", "120"),
		new Ingrediente("Pies de cerdo","0", "290"),
		new Ingrediente("Pollo, Hígado","0", "129"),
		new Ingrediente("Pollo, Muslo","0", "186"),
		new Ingrediente("Pollo","0", "134"),
		new Ingrediente("Salami","0", "325"),
		new Ingrediente("Salchicha Frankfurt","0", "315"),
		new Ingrediente("Salchichón","0", "294"),
		new Ingrediente("Ternera","0", "181"),
		new Ingrediente("Ternera, chuleta","0", "168"),
		new Ingrediente("Ternera, hígado","0", "140"),
		new Ingrediente("Ternera, lengua","0", "207"),
		new Ingrediente("Ternera, riñón","0", "86"),
		new Ingrediente("Ternera, sesos","0", "125"),
		new Ingrediente("Ternera, solomillo","0", "290"),
		new Ingrediente("Tira de asado","0", "401"),
		new Ingrediente("Tripas","0", "100"),
		new Ingrediente("Vacuno, Hígado","0", "129"),
		new Ingrediente("Almejas","0", "50"),
		new Ingrediente("Anchoas","0", "175"),
		new Ingrediente("Anguilas","0", "200"),
		new Ingrediente("Atún en lata con aceite vegetal","0", "280"),
		new Ingrediente("Atún en lata con agua","0", "127"),
		new Ingrediente("Atún fresco","0", "225"),
		new Ingrediente("Bacalao fresco","0", "74"),
		new Ingrediente("Bacalao seco","0", "322"),
		new Ingrediente("Besugo","0", "118"),
		new Ingrediente("Caballa","0", "153"),
		new Ingrediente("Calamar","0", "82"),
		new Ingrediente("Cangrejo","0", "85"),
		new Ingrediente("Caviar","0", "233"),
		new Ingrediente("Congrio","0", "112"),
		new Ingrediente("Dorada","0", "80"),
		new Ingrediente("Gallo","0", "73"),
		new Ingrediente("Gambas","0", "96"),
		new Ingrediente("Langosta","0", "67"),
		new Ingrediente("Langostino","0", "96"),
		new Ingrediente("Lenguado","0", "73"),
		new Ingrediente("Lubina","0", "118"),
		new Ingrediente("Lucio","0", "81"),
		new Ingrediente("Mejillón","0", "74"),
		new Ingrediente("Merluza","0", "86"),
		new Ingrediente("Mero","0", "118"),
		new Ingrediente("Ostras","0", "80"),
		new Ingrediente("Pejerrey","0", "87"),
		new Ingrediente("Pez espada","0", "109"),
		new Ingrediente("Pulpo","0", "57"),
		new Ingrediente("Rodaballo","0", "81"),
		new Ingrediente("Salmón","0", "172"),
		new Ingrediente("Salmón ahumado","0", "154"),
		new Ingrediente("Salmonete","0", "97"),
		new Ingrediente("Sardina en lata con aceite vegetal","0", "192"),
		new Ingrediente("Sardinas","0", "151"),
		new Ingrediente("Trucha","0", "94"),
		new Ingrediente("Azúcar","0", "380"),
		new Ingrediente("Cacao en polvo con azúcar instantáneo","0", "366"),
		new Ingrediente("Caramelos","0", "378"),
		new Ingrediente("Chocolate con leche","0", "550"),
		new Ingrediente("Chocolate sin leche","0", "530"),
		new Ingrediente("Crema chocolate con avellanas","0", "549"),
		new Ingrediente("Dulce de membrillo","0", "215"),
		new Ingrediente("Helados de agua","0", "139"),
		new Ingrediente("Mermeladas con azúcar","0", "280"),
		new Ingrediente("Mermeladas sin azúcar","0", "145"),
		new Ingrediente("Miel","0", "300"),
		new Ingrediente("Arroz blanco","0", "354"),
		new Ingrediente("Arroz integral","0", "350"),
		new Ingrediente("Avena","0", "367"),
		new Ingrediente("Cebada","0", "373"),
		new Ingrediente("Centeno","0", "350"),
		new Ingrediente("Cereales con chocolate","0", "358"),
		new Ingrediente("Cereales desayuno, con miel","0", "386"),
		new Ingrediente("Copos de maíz","0", "350"),
		new Ingrediente("Harina de maíz","0", "349"),
		new Ingrediente("Harina de trigo integral","0", "340"),
		new Ingrediente("Harina de trigo refinada","0", "353"),
		new Ingrediente("Pan de centeno","0", "241"),
		new Ingrediente("Pan de trigo blanco","0", "255"),
		new Ingrediente("Pan de trigo integral","0", "239"),
		new Ingrediente("Pan de trigo molde blanco","0", "233"),
		new Ingrediente("Pan de trigo molde integral","0", "216"),
		new Ingrediente("Pasta al huevo","0", "368"),
		new Ingrediente("Pasta de sémola","0", "361"),
		new Ingrediente("Polenta","0", "358"),
		new Ingrediente("Sémola de trigo","0", "368"),
		new Ingrediente("Yuca","0", "338"),
		new Ingrediente("Garbanzos","0", "361"),
		new Ingrediente("Judías","0", "343"),
		new Ingrediente("Lentejas","0", "336"),
		new Ingrediente("Clara","0", "48"),
		new Ingrediente("Huevo duro","0", "147"),
		new Ingrediente("Huevo entero","0", "162"),
		new Ingrediente("Yema","0", "368"),
		new Ingrediente("Bizcocho","0", "456"),
		new Ingrediente("Croissant chocolate","0", "469"),
		new Ingrediente("Croissant, donut","0", "456"),
		new Ingrediente("Galletas de chocolate","0", "524"),
		new Ingrediente("Galletas de mantequilla tipo \"Danesas\"","0", "397"),
		new Ingrediente("Galletas saladas","0", "464"),
		new Ingrediente("Magdalenas","0", "469"),
		new Ingrediente("Pasta de hojaldre cocida","0", "565"),
		new Ingrediente("Pastel de manzana","0", "311"),
		new Ingrediente("Pastel de manzana, masa hojaldre","0", "456"),
		new Ingrediente("Pastel de queso","0", "414"),
		new Ingrediente("Agua ardiente","0", "280"),
		new Ingrediente("Agua tónica","0", "34"),
		new Ingrediente("Anís","0", "312"),
		new Ingrediente("Batido lácteo de cacao","0", "100"),
		new Ingrediente("Cacao en polvo sin azúcar a la taza","0", "439"),
		new Ingrediente("Café","0", "1"),
		new Ingrediente("Cerveza negra","0", "37"),
		new Ingrediente("Cerveza rubia","0", "45"),
		new Ingrediente("Champaña demi-sec","0", "90"),
		new Ingrediente("Champaña dulce","0", "118"),
		new Ingrediente("Champaña seca","0", "85"),
		new Ingrediente("Coñac, brandy","0", "243"),
		new Ingrediente("Crema de cacao","0", "260"),
		new Ingrediente("Daiquiri","0", "122"),
		new Ingrediente("Gin & Tónica","0", "76"),
		new Ingrediente("Ginebra","0", "244"),
		new Ingrediente("Leche de almendras","0", "335"),
		new Ingrediente("Licor de caña","0", "273"),
		new Ingrediente("Piña colada","0", "194"),
		new Ingrediente("Pisco","0", "210"),
		new Ingrediente("Refrescos carbonatados","0", "48"),
		new Ingrediente("Ron","0", "244"),
		new Ingrediente("Sidra dulce","0", "33"),
		new Ingrediente("Sidra seca","0", "35"),
		new Ingrediente("Té","0", "1"),
		new Ingrediente("Vermouth amargo","0", "112"),
		new Ingrediente("Vermouth dulce","0", "160"),
		new Ingrediente("Vino de mesa","0", "70"),
		new Ingrediente("Vino dulce, jerez","0", "160"),
		new Ingrediente("Vino oporto","0", "160"),
		new Ingrediente("Vodka","0", "315"),
		new Ingrediente("Whisky","0", "244"),
		new Ingrediente("Aceite de girasol","0", "900"),
		new Ingrediente("Aceite de oliva","0", "900"),
		new Ingrediente("Manteca","0", "670"),
		new Ingrediente("Mantequilla","0", "752"),
		new Ingrediente("Margarina vegetal","0", "752"),
		new Ingrediente("Bechamel","0", "115"),
		new Ingrediente("Caldos concentrados","0", "259"),
		new Ingrediente("Ketchup","0", "98"),
		new Ingrediente("Mayonesa","0", "718"),
		new Ingrediente("Mayonesa light","0", "374"),
		new Ingrediente("Mostaza","0", "15"),
		new Ingrediente("Salsa de soja","0", "61"),
		new Ingrediente("Salsa de tomate en conserva","0", "86"),
		new Ingrediente("Sofrito","0", "116"),
		new Ingrediente("Vinagres","0", "8")
	};

}

